# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a8d0778958b131a173795f17104b0420974f96764b9a68640bef13d2b38e0f58b7ce2c6647b561c673e7dafc0bc62d8f68e034a782f1f5fb13604c3ef010601

test:
  secret_key_base: 8eb48ad2a230f1fc2b85cf165c78c2785ceb181be77a1c7d559dbfc81b7e06e9f2e6891b0e77d0efe1e0dd7ab2e7ab25f42fb8c12d372c5db9b732e2adccb996

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
